using DesktopRelay.Core;
using System.Net;
using System.Net.Sockets;
using System.Text;
static void Check(bool value,string name) { if (!value) throw new Exception(name); Console.WriteLine("PASS " + name); }
static async Task<string> Header(Stream s) { var b = new byte[1]; var text = new StringBuilder(); while (!text.ToString().EndsWith("\r\n\r\n")) { if (await s.ReadAsync(b) == 0) break; text.Append((char)b[0]); } return text.ToString(); }
static Task Send(Stream s,string text) => s.WriteAsync(Encoding.ASCII.GetBytes(text)).AsTask();
static async Task<string> Request(int port,string text) { using var c = new TcpClient(); await c.ConnectAsync(IPAddress.Loopback,port); await Send(c.GetStream(),text); var response = ""; string part; do { part=await Header(c.GetStream()).WaitAsync(TimeSpan.FromSeconds(15)); response+=part; } while (part.StartsWith("HTTP/1.1 1")); return response; }
static async Task<TcpClient> Tunnel(int port,int target) { var c = new TcpClient(); await c.ConnectAsync(IPAddress.Loopback,port); await Send(c.GetStream(),$"CONNECT localhost:{target} HTTP/1.1\r\nHost: localhost:{target}\r\nProxy-Authorization: secret\r\n\r\n"); var h = await Header(c.GetStream()); Check(h.Contains("200"),"CONNECT established"); return c; }
static async Task Echo(TcpClient c,string payload,string expected) { await Send(c.GetStream(),payload); var bytes = new byte[Encoding.ASCII.GetByteCount(expected)]; await c.GetStream().ReadExactlyAsync(bytes).AsTask().WaitAsync(TimeSpan.FromSeconds(5)); Check(Encoding.ASCII.GetString(bytes)==expected,"echo " + expected); }
await using var a = new Fake("A"); await using var b = new Fake("B"); await using var echo = new Fake(""); await using var reject = new Fake("reject"); await using var hints = new Fake("hints"); await using var stall = new Fake("stall");
var messages=new System.Collections.Concurrent.ConcurrentQueue<string>(); await using var relay = new RelayServer(messages.Enqueue); relay.Start(0); Check(relay.Port > 0,"ephemeral IPv4 listener");
Check((await Request(relay.Port,$"CONNECT localhost:{echo.Port} HTTP/1.1\r\n\r\n")).StartsWith("HTTP/1.1 503"),"default disabled rejects CONNECT"); Check(echo.AcceptedCount==0,"disabled opens no target socket"); relay.SwitchRoute(new(RouteMode.HttpProxy,"127.0.0.1",a.Port)); using var old = await Tunnel(relay.Port,echo.Port); await Echo(old,"first","Afirst");
relay.SwitchRoute(new(RouteMode.HttpProxy,"127.0.0.1",b.Port)); using var newer = await Tunnel(relay.Port,echo.Port); await Echo(newer,"new","Bnew"); await Echo(old,"old","Aold"); Check(!a.LastHeader.Contains("secret"),"client proxy credentials stripped");
relay.SwitchRoute(new(RouteMode.Direct)); using var direct = await Tunnel(relay.Port,echo.Port); await Echo(direct,"direct","direct");
var bulk = Enumerable.Range(0,1048576).Select(i => (byte)(i % 251)).ToArray(); var bulkRead=new byte[bulk.Length]; var writing=direct.GetStream().WriteAsync(bulk).AsTask(); await direct.GetStream().ReadExactlyAsync(bulkRead).AsTask().WaitAsync(TimeSpan.FromSeconds(10)); await writing; Check(bulk.SequenceEqual(bulkRead),"1MB backpressure and binary transparency"); var directStream=direct.GetStream(); await Send(directStream,"half"); direct.Client.Shutdown(SocketShutdown.Send); var tail = new byte[4]; await directStream.ReadExactlyAsync(tail); Check(Encoding.ASCII.GetString(tail)=="half","half-close preserves final response");
Check((await Request(relay.Port,$"GET http://localhost:{b.Port}/hello?q=1 HTTP/1.1\r\nHost: x\r\nProxy-Authorization: secret\r\nConnection: X-Test\r\nX-Test: remove\r\n\r\n")).Contains("OK"),"HTTP direct"); Check(b.LastHeader.StartsWith("GET /hello?q=1") && !b.LastHeader.Contains("secret") && !b.LastHeader.Contains("X-Test"),"origin form and hop-by-hop removal");
relay.SwitchRoute(new(RouteMode.HttpProxy,"127.0.0.1",a.Port)); Check((await Request(relay.Port,$"GET http://localhost:{b.Port}/hello HTTP/1.1\r\nHost: x\r\n\r\n")).Contains("OK"),"HTTP upstream"); Check(a.LastHeader.StartsWith("GET http://"),"upstream absolute form");
Check((await Request(relay.Port,$"POST http://localhost:{echo.Port}/ HTTP/1.1\r\nContent-Length: 4\r\n\r\nbody")).Contains("OK"),"Content-Length body"); Check(a.LastBody=="body","body bytes preserved after header");
Check((await Request(relay.Port,$"POST http://localhost:{echo.Port}/ HTTP/1.1\r\nTransfer-Encoding: chunked\r\n\r\n4\r\nbody\r\n0\r\n\r\n")).Contains("OK"),"chunked body");
await a.DisposeAsync(); var closeByte=new byte[1]; Check(await old.GetStream().ReadAsync(closeByte).AsTask().WaitAsync(TimeSpan.FromSeconds(5))==0,"closing A ends old tunnel"); await Echo(newer,"retained","Bretained"); relay.SwitchRoute(new(RouteMode.HttpProxy,"127.0.0.1",reject.Port)); Check((await Request(relay.Port,"CONNECT localhost:80 HTTP/1.1\r\n\r\n")).StartsWith("HTTP/1.1 502"),"upstream rejection never advertises 200");
var unused = new TcpListener(IPAddress.Loopback,0); unused.Start(); var closedPort = ((IPEndPoint)unused.LocalEndpoint).Port; unused.Stop(); relay.SwitchRoute(new(RouteMode.HttpProxy,"127.0.0.1",closedPort)); Check((await Request(relay.Port,"CONNECT localhost:80 HTTP/1.1\r\n\r\n")).Contains("502"),"upstream connect failure");
Check((await Request(relay.Port,"nonsense\r\n\r\n")).Contains("400"),"malformed request"); Check((await Request(relay.Port,"GET https://example.test/ HTTP/1.1\r\n\r\n")).Contains("400"),"unsupported target scheme"); try { Check((await Request(relay.Port,"GET http://x/ HTTP/1.1\r\nX: " + new string('a',16400)+"\r\n\r\n")).Contains("400"),"oversized header"); } catch (IOException) { Console.WriteLine("PASS oversized header rejected by reset"); }
foreach (var text in new[]{"socks5://localhost:1","http://u:p@localhost:1","http://localhost:1/path"}) { try { Route.ParseProxy(text); throw new Exception("accepted invalid proxy"); } catch (ArgumentException) { Console.WriteLine("PASS rejected proxy " + text.Split(':')[0]); } }
try { relay.SwitchRoute(new(RouteMode.HttpProxy,"localhost",relay.Port)); throw new Exception("self loop accepted"); } catch (ArgumentException) { Console.WriteLine("PASS recursive route rejected"); }
await using var conflict = new RelayServer(); try { conflict.Start(relay.Port); throw new Exception("port conflict accepted"); } catch (SocketException) { Console.WriteLine("PASS occupied port rejected"); }
relay.SwitchRoute(new(RouteMode.Direct)); Check((await Request(relay.Port,$"GET http://localhost:{hints.Port}/ HTTP/1.1\r\n\r\n")).Contains("103 Early Hints"),"HTTP direct forwards 103");
relay.SwitchRoute(new(RouteMode.HttpProxy,"127.0.0.1",hints.Port)); var hintResponse=await Request(relay.Port,"GET http://example.test/ HTTP/1.1\r\n\r\n"); Check(hintResponse.Contains("103 Early Hints") && hintResponse.Contains("200 OK"),"HTTP proxy forwards 103 and final 200");
while(messages.TryDequeue(out _)) {} relay.SwitchRoute(new(RouteMode.HttpProxy,"localhost.",relay.Port)); Check((await Request(relay.Port,"CONNECT example.test:443 HTTP/1.1\r\n\r\n")).StartsWith("HTTP/1.1 502"),"resolved localhost alias recursion blocked"); Check(messages.Any(m => m.Contains("phase=upstream-tcp") && m.EndsWith(": IOException")),"endpoint guard detects resolved loopback");
relay.SwitchRoute(new(RouteMode.HttpProxy,"127.0.0.1",stall.Port)); var clock=System.Diagnostics.Stopwatch.StartNew(); Check((await Request(relay.Port,"CONNECT example.test:443 HTTP/1.1\r\n\r\n")).StartsWith("HTTP/1.1 502") && clock.Elapsed.TotalSeconds is >= 9 and < 14,"upstream handshake timeout bounded at 10s");
relay.SwitchRoute(new(RouteMode.Disabled)); Check((await Request(relay.Port,$"GET http://localhost:{hints.Port}/ HTTP/1.1\r\n\r\n")).StartsWith("HTTP/1.1 503"),"explicit disabled rejects ordinary HTTP");
messages.Clear(); relay.SwitchRoute(new(RouteMode.HttpProxy,"127.0.0.1",reject.Port));
await Request(relay.Port,"CONNECT example.test:443 HTTP/1.1\r\n\r\n");
Check(messages.Any(m => m.Contains("upstreamStatus=403") && m.Contains("phase=proxy-connect")), "CONNECT rejection records actual upstream status");
Check(messages.Any(m => m.Contains("id=") && m.Contains("target=example.test:443")), "connection diagnosis correlates target and connection id");
Check(!messages.Any(m => m.Contains("secret")), "diagnostic messages exclude credentials");
await relay.StopAsync(); Check(relay.ActiveConnections==0,"stop drains connections"); Console.WriteLine("ALL CORE TESTS PASS");
sealed class Fake : IAsyncDisposable
{
    readonly TcpListener listener = new(IPAddress.Loopback,0); readonly CancellationTokenSource cancel = new(); readonly List<TcpClient> clients = new(); readonly Task loop; readonly string marker; bool disposed;
    public int AcceptedCount; public int Port { get; } public string LastHeader=""; public string LastBody="";
    public Fake(string marker) { this.marker=marker; listener.Start(); Port=((IPEndPoint)listener.LocalEndpoint).Port; loop=Loop(); }
    async Task Loop() { try { while (!cancel.IsCancellationRequested) { var c=await listener.AcceptTcpClientAsync(cancel.Token); Interlocked.Increment(ref AcceptedCount); lock(clients) clients.Add(c); _=Serve(c); } } catch(OperationCanceledException) {} }
    async Task Serve(TcpClient c) { try { using(c) { var s=c.GetStream(); if(marker == "") { var eb=new byte[32768]; int en; while((en=await s.ReadAsync(eb,cancel.Token))>0) await s.WriteAsync(eb.AsMemory(0,en),cancel.Token); return; } var bytes=new List<byte>(); var one=new byte[1]; while (bytes.Count<20000) { if(await s.ReadAsync(one,cancel.Token)==0)return; bytes.Add(one[0]); if(bytes.Count>=4 && Encoding.ASCII.GetString(bytes.TakeLast(4).ToArray())=="\r\n\r\n")break; } LastHeader=Encoding.ASCII.GetString(bytes.ToArray());
        if(LastHeader.StartsWith("CONNECT")) { if(marker=="stall") { await Task.Delay(Timeout.Infinite,cancel.Token); return; } await s.WriteAsync(Encoding.ASCII.GetBytes(marker=="reject"?"HTTP/1.1 403 Forbidden\r\nContent-Length: 0\r\n\r\n":"HTTP/1.1 200 OK\r\n\r\n")); if(marker=="reject")return; var buffer=new byte[32768]; int n; while((n=await s.ReadAsync(buffer,cancel.Token))>0) { await s.WriteAsync(Encoding.ASCII.GetBytes(marker),cancel.Token); await s.WriteAsync(buffer.AsMemory(0,n),cancel.Token); } }
        else { var lengthLine=LastHeader.Split("\r\n").FirstOrDefault(x=>x.StartsWith("Content-Length:",StringComparison.OrdinalIgnoreCase)); if(lengthLine!=null) { var body=new byte[int.Parse(lengthLine.Split(':')[1])]; await s.ReadExactlyAsync(body,cancel.Token); LastBody=Encoding.ASCII.GetString(body); } if(LastHeader.Contains("Transfer-Encoding: chunked")) { var body=new StringBuilder(); while(!body.ToString().EndsWith("0\r\n\r\n")) { await s.ReadExactlyAsync(one,cancel.Token); body.Append((char)one[0]); } LastBody=body.ToString(); } if(marker=="hints") await s.WriteAsync(Encoding.ASCII.GetBytes("HTTP/1.1 103 Early Hints\r\nLink: </asset>; rel=preload\r\n\r\n")); await s.WriteAsync(Encoding.ASCII.GetBytes("HTTP/1.1 200 OK\r\nContent-Length: 2\r\nConnection: close\r\n\r\nOK")); }
    } } catch(Exception ex) when(ex is IOException or SocketException or OperationCanceledException or ObjectDisposedException) {} }
    public async ValueTask DisposeAsync() { if(disposed)return; disposed=true; cancel.Cancel(); listener.Stop(); lock(clients)foreach(var c in clients)c.Dispose(); await loop; cancel.Dispose(); }
}
